# Generated by Django 4.2 on 2023-06-07 08:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeid', models.IntegerField()),
                ('employeename', models.CharField(max_length=50)),
                ('dategiven', models.DateField(default=datetime.date.today)),
                ('submissiondate', models.DateField()),
                ('tasktitle', models.CharField(max_length=100)),
                ('taskinfo', models.TextField(max_length=500)),
            ],
        ),
    ]
